version: "3"
services:
  db_core:
    image: mysql:5
    container_name: mysql_core
    volumes:
      - ./core:/app
      - ./core/.database/data:/var/lib/mysql
      - ./core/.database/custom.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=qwer
      - MYSQL_USER=root
      - MYSQL_PASSWORD=qwer
    networks:
      - core
    restart: unless-stopped
  jdk_core:
    image: maven:3.5-jdk-8-alpine
    working_dir: /app
    container_name: jdk_core
    volumes:
      - ./core:/app
      - ./.m2:/root/.m2
    ports:
      - 8808:8080
    command: mvn clean spring-boot:run
    networks:
      - core
    restart: unless-stopped
    depends_on:
      - db_core

  db_review:
    image: mysql:5
    container_name: mysql_review
    volumes:
      - ./review:/app
      - ./review/.database/data:/var/lib/mysql
      - ./review/.database/custom.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=qwer
      - MYSQL_USER=root
      - MYSQL_PASSWORD=qwer
    networks:
      - review
    restart: unless-stopped
  jdk_review:
    image: maven:3.5-jdk-8-alpine
    working_dir: /app
    container_name: jdk_review
    volumes:
      - ./review:/app
      - ./.m2:/root/.m2
    ports:
      - 8809:8080
    command: mvn clean spring-boot:run
    networks:
      - review
    restart: unless-stopped
    depends_on:
      - db_review

networks:
  core:
    driver: bridge
  review:
    driver: bridge