version: "3"
services:
  db:
    image: mysql:5
    container_name: mysql
    volumes:
      - .:/app
      - .database/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=qwer
      - MYSQL_USER=root
      - MYSQL_PASSWORD=qwer
    ports:
      - 3307:3306
    restart: unless-stopped
  jdk:
    image: maven:3.5-jdk-8
    working_dir: /app
    container_name: jdk
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    ports:
      - 8808:8080
    command: mvn clean spring-boot:run
    restart: unless-stopped
    depends_on:
      - db