spring:
  datasource:
    url: jdbc:mysql://db/blib_core?createDatabaseIfNotExist=true
    username: root
    password: qwer
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    locations: filesystem:/app/src/main/resources/db/migration